server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ferrefull}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"